---
title: "New Vaccine Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, include = FALSE)
knitr::opts_chunk$set(echo = FALSE)
library(gt)
library(tidyverse)
library(highcharter)
library(readxl)
library(sf)
library(ggtext)
library(janitor)
library(ggforce)
library(mapboxapi)
library(leaflet)
library(tidycensus)
library(lbjdata)
library(png)
library(tinter)
library(tmap)
library(tmaptools)
options(tigris_use_cache = TRUE)

today <- Sys.Date()
src <- "https://dshs.texas.gov/immunize/covid19/COVID-19-Vaccine-Data-by-County.xls" # URL For Daily COVID Data
lcl <- basename(src)
filepath <- paste0(today,"_",lcl,"x")
download.file(url = src, destfile = filepath) # Downloads The Data
today_lbl <- format(Sys.Date(), format = "%b %d, %Y")
# today_lbl <- format(Sys.Date(), format = "%b %d, %Y")
time_lbl <- format(Sys.time(), format = "%I:%M %p")

src_zcta <- "https://dshs.texas.gov/coronavirus/TexasCOVID19VaccinesbyZIP.xlsx"
lcl_zcta <- basename(src_zcta)
filepath_zcta <- paste0("raw_data/", today,"_",lcl_zcta)
download.file(url = src_zcta, destfile = filepath_zcta) # Downloads The Data

I35 <- st_read("raw_data/spatial/I35_HighwayATX.shp") %>% 
  st_transform(crs = 4326)

arterials <- st_read("raw_data/spatial/arterials/CENART.shp") %>% 
  st_transform(crs = 4326) %>% 
  filter(NAME != "IH 35",
         str_detect(TYPE, "HWY|BLVD"),
         SIZE == "MAJOR")

capcog <- st_read("raw_data/spatial/CAPCOG_Counties.shp") %>% 
  st_transform(crs = 4326) %>% 
  filter(COUNTY != "TRAVIS")

img <- readPNG("raw_data/spatial/I35.png")

# tx_zips <- tigris::zctas(state="TX",cb=TRUE) 

travis_county_sf <- tigris::counties(state="TX") %>% filter(GEOID=="48453")

bgmap_travis <- travis_county_sf %>% 
  st_transform(crs = 4326)

mapRange_travis_cnty <- c(range(st_coordinates(bgmap_travis)[,1]),
                          range(st_coordinates(bgmap_travis)[,2]))




```

## Zip Code Map

```{r cars, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}

full_zips_list <- "78617|78641|78645|78652|78653|78660|78701|78702|78703|78704|78719|78721|78722|78723|78724|78725|78727|78728|78730|78731|78732|78733|78734|78735|78736|78738|78739|78741|78742|78743|78744|78745|78746|78747|78748|78749|78750|78751|78752|78753|78754|78756|78757|78758|78759|78654|78610|78621|78615|78669|78737|78620|78726|78705|78712|78613|78664|78612|78663"

inc_to_poverty_lbls <- load_variables(2019, "acs5") %>% 
  filter(str_detect(name,"^C17002")) %>% 
  mutate(label = str_remove(label, "Estimate!!"),
         label = str_remove(label, "^Total:!!")) %>% 
  select(variable=name, label, -concept)

zips <- tigris::zctas(cb=TRUE, state = "TX")

inc_to_poverty <- get_acs(geography = "zcta", table = "C17002", summary_var = "C17002_001",  state = "TX", geometry = TRUE) %>% 
  left_join(inc_to_poverty_lbls, by = "variable") %>% 
  filter(variable!="C17002_001") %>% 
  mutate(group = case_when(
    label == "Under .50" ~ "Below 200% of FPL",   
    label == ".50 to .99" ~ "Below 200% of FPL",  
    label == "1.00 to 1.24" ~ "Below 200% of FPL",  
    label == "1.25 to 1.49" ~ "Below 200% of FPL",  
    label == "1.50 to 1.84" ~ "Below 200% of FPL",  
    label == "1.85 to 1.99" ~ "Below 200% of FPL",  
    label == "2.00 and over" ~ "200% and Above"
  )) %>% 
  group_by(geoid = GEOID, summary_est, group) %>% 
  summarise(grouped_est = sum(estimate)) %>% 
  select(1,3,4,2, geometry) %>% 
  mutate(group_rate = round((grouped_est/summary_est)*100, digits=2)) %>% 
  filter(group!="200% and Above")

pop_16_zcta <- get_acs(geography="zcta", 
                       variables = "B23027_001",
                       state = "TX",
                       geometry = TRUE) %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(geoid, pop_16_plus = estimate)

vaccine_summ_zcta <- read_excel(filepath_zcta, sheet = 2, skip=0) %>% 
  clean_names() %>% 
  filter(str_detect(recipient_zip_code, full_zips_list)) %>% 
  left_join(inc_to_poverty, by =c("recipient_zip_code"="geoid")) %>% 
  drop_na(geometry) %>% 
  mutate(vaccine_doses_administered = as.numeric(vaccine_doses_administered)) %>% 
  st_as_sf()

vaccine_summ_zcta %>% 
  ggplot() +
  rcartocolor::scale_fill_carto_c(type = "sequential", palette = "Geyser", direction = -1,
                                  labels = scales::number_format(accuracy=1, scale = 1, big.mark = ",")) +
  geom_sf(aes(fill=vaccine_doses_administered)) +
  coord_sf(datum=NA) +
  theme_lbj(legend_position = "bottom") +
  guides(fill = guide_colorbar(title = "Vaccine Doses Administered, by Zip Code", title.position = "top",
                               barwidth = 40, ticks=TRUE, nbin = 10000, frame.colour = "black", frame.linewidth = 1, 
                               barheight = .9, direction="horizontal", title.hjust = .5), colour = FALSE) +
  labs(title = "Vaccine Doses Administered, by Zip Code in Travis County",
       subtitle = "Zip Codes Shown: Travis County",
       caption = "Source: Texas Department of State Health Services") +
  ggsave("figures/doses_administered_zcta.png", device="png", dpi=300, width = 12, height = 9)

mapRange_travis_cnty <- c(range(st_coordinates(vaccine_summ_zcta)[,1]),
                          range(st_coordinates(vaccine_summ_zcta)[,2]))

 

vaccine_summ_zcta %>% 
  mutate(people_fully_vaccinated = as.numeric(people_fully_vaccinated)) %>% 
  ggplot() +
  rcartocolor::scale_fill_carto_c(type = "sequential", palette = "Geyser", direction = -1,
                                  labels = scales::number_format(accuracy=1, scale = 1, big.mark = ",")) +
  geom_sf(aes(fill=people_fully_vaccinated)) +
  coord_sf(datum=NA) +
  theme_lbj(legend_position = "bottom") +
  guides(fill = guide_colorbar(title = "People Fully Vaccinated, by Zip Code", title.position = "top",
                               barwidth = 40, ticks=TRUE, nbin = 10000, frame.colour = "black", frame.linewidth = 1, 
                               barheight = .9, direction="horizontal", title.hjust = .5), colour = FALSE) +
  labs(title = "People Fully Vaccinated, by Zip Code in Travis County",
       subtitle = "Zip Codes Shown: Travis County",
       caption = "Source: Texas Department of State Health Services") +
  ggsave("figures/people_fully_vaccinated.png", device="png", dpi=300, width = 12, height = 9)

library(biscale)
library(cowplot)

data <- bi_class(vaccine_summ_zcta, x = vaccine_doses_administered, y = group_rate, style = "quantile", dim = 3)

# create map
map <- ggplot() +
  geom_sf(data = vaccine_summ_zcta, mapping = aes(color = bi_class), show.legend = FALSE) +
  bi_scale_color(pal = "DkBlue", dim = 3) +
  bi_theme()

finalPlot <- ggdraw() +
  draw_plot(map, 0, 0, 1, 1) 

```

## TMAP Version

```{r mapping assets, eval=FALSE, include=FALSE}
I35 <- st_read("spatial/I35_HighwayATX.shp") %>% 
  st_transform(crs = 4326)

arterials <- st_read("spatial/arterials/CENART.shp") %>% 
  st_transform(crs = 4326) %>% 
  filter(NAME != "IH 35",
         str_detect(TYPE, "HWY|BLVD"),
         SIZE == "MAJOR")

capcog <- st_read("spatial/CAPCOG_Counties.shp") %>% 
  st_transform(crs = 4326) %>% 
  filter(COUNTY != "TRAVIS")

img <- readPNG("spatial/I35.png")

tx_zips <- tigris::zctas(state="TX",cb=TRUE) 

sf_counties <- tigris::counties(state="TX") %>% filter(GEOID=="48453")

vaccine_summ_zcta <- read_excel(filepath_zcta, sheet = 2, skip=0) %>% 
  clean_names() %>% 
  filter(str_detect(recipient_zip_code, full_zips_list)) %>% 
  left_join(inc_to_poverty, by =c("recipient_zip_code"="geoid")) %>% 
  drop_na(geometry) %>% 
  mutate(vaccine_doses_administered = as.numeric(vaccine_doses_administered)) %>% 
  left_join(pop_16_zcta, by = c("recipient_zip_code"="geoid")) %>% 
  mutate(vax_administered_per_cap = round((as.numeric(vaccine_doses_administered)/pop_16_plus)*1000, digits = 4)) %>% 
  st_as_sf()
```

```{r eval=FALSE, fig.height=4, message=FALSE, warning=FALSE, include=FALSE, layout="l-page", paged.print=FALSE}

# For ArcGIS Data, The service ID is the key that goes after the datasets directory. Then use the 'ID' provided to pull the data into whatever format you want. For ATX, visit this site: https://services.arcgis.com/0L95CJ0VTaxqcmED/ArcGIS/rest/services/web0723/FeatureServer

atx_covid_zips_cases <- readr::read_csv("https://opendata.arcgis.com/datasets/4d913cdf3d894c3898696a7216e44180_02.csv") %>% 
  janitor::clean_names() %>% 
  dplyr::mutate(zipcode=as.character(zipcode))

atx_zips_by_cases_sf <- atx_covid_zips_cases %>%
  dplyr::left_join(tx_zips, by=c("zipcode"="GEOID10")) %>% 
  dplyr::select(zipcode, count, geometry) %>% 
  filter(count > 2) %>% 
  drop_na(count) %>% 
  sf::st_as_sf() %>% 
  st_transform(crs="ESRI:102339")

# cuts <- c(0,100,200,300,400,500,600)

tmap_mode("plot")

tm_shape(vaccine_summ_zcta, bbox = travis_county_sf, unit = "miles") +
  tm_fill("vax_administered_per_cap",
          title="Cases", 
          # breaks =cuts, 
          fontfamily = "Graphik Bold",
          legend.hist = FALSE,
          palette = "RdBu") +
  tm_shape(sf_counties) +
  tm_borders(lwd = 2) +
  tm_shape(I35, name = "I-35") +
  tm_lines(lwd = 3, col = "NAME", 
           palette="#d73a49", 
           title.col="Streets") +
  tm_shape(arterials) +
  tm_lines(lwd = .5, 
           col = "#9d9d9d") +
  tm_compass(type = "arrow",
             size= 1.5, bg.alpha = .6,
             color.dark = "#9d9d9d",
             position = c("right", "TOP")) +
  tm_scale_bar(color.dark = "gray60", 
               size = .5, 
               breaks = c(5,10),
               position = c("right", "bottom")) + 
  tm_layout(main.title = "COVID-19 Cases in Austin",
            main.title.size = 1.2,   
            main.title.fontfamily  = "Graphik Bold",
            main.title.position = c("center", "top"),
            title = " As of: Aug 13",
            title.size = 0.7,   
            title.fontfamily  = "Graphik Light",
            title.position = c("center", "top"),
            title.bg.color = "#2d2d2d",
            title.color = "white",
            fontfamily = "Graphik Regular",
            legend.outside = FALSE,
            legend.position = c("left", "bottom"),
            legend.title.fontfamily  = "Graphik Bold",
            legend.title.size = 1,
            legend.text.size = .5,
            legend.frame =  TRUE,
            legend.bg.color = "white",
            attr.outside = FALSE,
            asp = 0,
            bg.color = "transparent",
            inner.margins=c(.04,.03, .02, .01), 
            frame=FALSE) +
  tm_credits(text = "Data: Austin Public Health | Map: Matt Worthington ", 
             bg.color = "white",
             # bg.alpha = NA,
             fontfamily = "Graphik Book",
             align= "right",
             position = c("center", "TOP"),
             size = .4)

```

## Poverty and Zips Analysis

```{r}

library(ggforce)

inc_to_poverty_lbls <- load_variables(2019, "acs5") %>% 
  filter(str_detect(name,"^C17002")) %>% 
  mutate(label = str_remove(label, "Estimate!!"),
         label = str_remove(label, "^Total:!!")) %>% 
  select(variable=name, label, -concept)

inc_to_poverty <- get_acs(geography = "zcta", table = "C17002", summary_var = "C17002_001",  state = "TX") %>% 
  left_join(inc_to_poverty_lbls, by = "variable") %>% 
  filter(variable!="C17002_001") %>% 
  mutate(group = case_when(
    label == "Under .50" ~ "Below 200% of FPL",   
    label == ".50 to .99" ~ "Below 200% of FPL",  
    label == "1.00 to 1.24" ~ "Below 200% of FPL",  
    label == "1.25 to 1.49" ~ "Below 200% of FPL",  
    label == "1.50 to 1.84" ~ "Below 200% of FPL",  
    label == "1.85 to 1.99" ~ "Below 200% of FPL",  
    label == "2.00 and over" ~ "200% and Above"
  )) %>% 
  group_by(geoid = GEOID, summary_est, group) %>% 
  summarise(grouped_est = sum(estimate)) %>% 
  select(1,3,4,2) %>% 
  mutate(group_rate = round((grouped_est/summary_est)*100, digits=2)) %>% 
  ungroup()

pop_16_zcta <- get_acs(geography="zcta", 
                       variables = "B23027_001",
                       state = "TX",
                       geometry = TRUE) %>% 
  clean_names() %>% 
  as_tibble() %>% 
  select(geoid, pop_16_plus = estimate)

vaccine_summ_zcta <- read_excel(filepath_zcta, sheet = 2, skip=0) %>% 
  clean_names() %>% 
  left_join(inc_to_poverty, by =c("recipient_zip_code"="geoid")) %>% 
  left_join(pop_16_zcta, by =c("recipient_zip_code"="geoid")) %>% 
  drop_na(grouped_est) %>% 
  filter(group != "200% and Above") %>%
  mutate(vaccine_doses_administered = as.numeric(vaccine_doses_administered)) %>% 
  mutate(vax_administered_per_cap = round((as.numeric(vaccine_doses_administered)/pop_16_plus)*1000, digits = 4)) %>% 
  filter(vax_administered_per_cap <= 1000)

pov_scatter <- ggplot(vaccine_summ_zcta, 
       aes(x= vax_administered_per_cap, y = group_rate, color = group_rate)) + 
  # facet_wrap(~group, scales = "free_x") +
  geom_point() +
  geom_smooth(method = "lm", show.legend = FALSE) +
  scale_y_continuous(label = scales::number_format(suffix="%")) +
  scale_x_continuous(label = scales::number_format(big.mark =",")) +
  theme_lbj(legend_position = c(.95,.9)) +
  theme(plot.margin = ggplot2::margin(t=15, r=15, b=15, l = 15)) +
  scale_color_distiller(type = "div", palette = "RdBu", aesthetics = "color") +
  guides(fill = guide_colorbar(title = "Share of Families Living Below 200% of Poverty", title.position = "top",
                               barwidth = 40, ticks=TRUE, nbin = 10000, frame.colour = "black", frame.linewidth = 1, 
                               barheight = .9, direction="horizontal", title.hjust = .5), colour = FALSE) +
  labs(title = "Zip Codes with Higher Rates of Poverty Tend to Have<br>Lower Doses Administered Per Capita",
       subtitle = "Lower Doses Administered Per Capita = For Every 1,000 Persons, How Many Doses Have Been Administered",
       y = "Share of Families Living Below 200% of FPL",
       x = "Doses Administered For Every 1,000 Persons",
       color = "Poverty Rate",
       alpha = "Population Size",
       caption = "Source: Zip Code Vaccine Administration Data courtesy of Texas Department of State Health Services\nSource: Population Aged 16+ and Poverty Estimates courtesy of the American Community Survey (2019 5-Yr Estimates) Produced by the US Census\nChart By: @mrworthington") +
  ggsave("figures/poverty_per_capita_doses_administered.png", device="png", dpi=300, width = 12, height = 8)

# plotly::ggplotly(pov_scatter)

# med_inc <- get_acs(geography = "zcta", summary_var = "B19013_001",  state = "TX") 

```

